sudo: required
language: generic
services:
        - docker

before_install:
        - docker build -t tejasdewan/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true tejasdewan/react-test npm run test -- --coverage

after_success:
        - docker build -t tejasdewan/multi-client ./client
        - docker build -t tejasdewan/multi-nginx ./nginx
        - docker build -t tejasdewan/multi-server ./server
        - docker build -t tejasdewan/multi-worker ./worker
        # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
        - docker images
        # Take images and push them to docker hub
        - docker push tejasdewan/multi-client
        - docker push tejasdewan/multi-nginx
        - docker push tejasdewan/multi-server
        - docker push tejasdewan/multi-worker
